---
# This workflow runs all of the very-long tests within main.py

name: Weekly Tests

on:
    # This is triggered weekly via the 'scheduler.yaml' workflow.
    workflow_dispatch:

jobs:

    get-date:
        runs-on: ubuntu-latest
        outputs:
            date: ${{ steps.date.outputs.date }}
        steps:
            - name: Get the current date
              id: date
              run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    # start running the very-long tests
    testlib-very-long-tests:
        strategy:
            fail-fast: false
            matrix:
                test-type: [gem5_library_example_tests, gem5_resources, stdlib, parsec_benchmarks, x86_boot_tests]
        runs-on: [self-hosted, linux, x64]
        container: ghcr.io/gem5/ubuntu-24.04_all-dependencies:latest
        timeout-minutes: 4320 # 3 days
        needs: get-date
        steps:
            - name: Clean runner
              run: rm -rf ./* || true rm -rf ./.??* || true rm -rf ~/.cache || true
            - uses: actions/checkout@v4

            - name: Cache build/ALL
              uses: actions/cache@v4
              with:
                  path: build/ALL
                  key: testlib-build-all-${{ needs.get-date.outputs.date }}
                  restore-keys: |
                      testlib-build-all

            - name: very-long ${{ matrix.test-type }}
              working-directory: ${{ github.workspace }}/tests
              run: ./main.py run gem5/${{ matrix.test-type }} --length very-long -j$(nproc) -vv
            - name: upload results
              if: success() || failure()
              uses: actions/upload-artifact@v4
              env:
                  MY_STEP_VAR: ${{ matrix.test-type }}_COMMIT.${{github.sha}}_RUN.${{github.run_id}}_ATTEMPT.${{github.run_attempt}}
              with:
                  name: ${{ env.MY_STEP_VAR }}
                  path: tests/testing-results
                  retention-days: 7
            - run: echo "This job's status is ${{ job.status }}."

    # The GPU tests are run in different jobs beacuse they take a long time to run. This way we can run them in parallel on different runners.
    gpu-test-hacc:
        runs-on: [self-hosted, linux, x64]
        container: ghcr.io/gem5/gcn-gpu:latest
        timeout-minutes: 720 # 12 hours
        needs: get-date

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: develop

            - name: Cache build/VEGA_X86
              uses: actions/cache@v4
              with:
                  path: build/VEGA_X86
                  key: testlib-build-vega-${{ needs.get-date.outputs.date }}
                  restore-keys: |
                      testlib-build-vega

            - name: Run Testlib GPU Tests
              working-directory: ${{ github.workspace }}/tests
              run: ./main.py run --length=very-long -vvv -j $(nproc) --host gcn_gpu --uid SuiteUID:tests/gem5/gpu/test_gpu_apu_se.py:gpu-apu-se-hacc-VEGA_X86-gcn_gpu-opt

            - name: Upload results
              if: success() || failure()
              uses: actions/upload-artifact@v4.0.0
              with:
                  name: gpu_tests_hacc_${{github.sha}}_RUN_${{github.run_id}}_ATTEMPT_${{github.run_attempt}}
                  path: tests/testing-results
                  retention-days: 7

    gpu-test-lulesh:
        runs-on: [self-hosted, linux, x64]
        container: ghcr.io/gem5/gcn-gpu:latest
        timeout-minutes: 720 # 12 hours
        needs: get-date

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: develop

            - name: Cache build/VEGA_X86
              uses: actions/cache@v4
              with:
                  path: build/VEGA_X86
                  key: testlib-build-vega-${{ needs.get-date.outputs.date }}
                  restore-keys: |
                      testlib-build-vega

            - name: Run Testlib GPU Tests
              working-directory: ${{ github.workspace }}/tests
              run: ./main.py run --length=very-long -vvv -j $(nproc) --host gcn_gpu --uid SuiteUID:tests/gem5/gpu/test_gpu_apu_se.py:gpu-apu-se-lulesh-VEGA_X86-gcn_gpu-opt

            - name: Upload results
              if: success() || failure()
              uses: actions/upload-artifact@v4.0.0
              with:
                  name: gpu_tests_lulesh_${{github.sha}}_RUN_${{github.run_id}}_ATTEMPT_${{github.run_attempt}}
                  path: tests/testing-results
                  retention-days: 7

    gpu-test-pannotia-bc:
        runs-on: [self-hosted, linux, x64]
        container: ghcr.io/gem5/gcn-gpu:latest
        timeout-minutes: 720 # 12 hours
        needs: get-date

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: develop

            - name: Cache build/VEGA_X86
              uses: actions/cache@v4
              with:
                  path: build/VEGA_X86
                  key: testlib-build-vega-${{ needs.get-date.outputs.date }}
                  restore-keys: |
                      testlib-build-vega

            - name: Run Testlib GPU Tests
              working-directory: ${{ github.workspace }}/tests
              run: ./main.py run --length=very-long -vvv -j $(nproc) --host gcn_gpu --uid SuiteUID:tests/gem5/gpu/test_gpu_pannotia.py:gpu-apu-se-pannotia-bc-1k-128k-VEGA_X86-gcn_gpu-opt

            - name: Upload results
              if: success() || failure()
              uses: actions/upload-artifact@v4.0.0
              with:
                  name: gpu_tests_pannotia_bc_${{github.sha}}_RUN_${{github.run_id}}_ATTEMPT_${{github.run_attempt}}
                  path: tests/testing-results
                  retention-days: 7

    gpu-test-pannotia-color-maxmin:
        runs-on: [self-hosted, linux, x64]
        container: ghcr.io/gem5/gcn-gpu:latest
        timeout-minutes: 720 # 12 hours
        needs: get-date

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: develop

            - name: Cache build/VEGA_X86
              uses: actions/cache@v4
              with:
                  path: build/VEGA_X86
                  key: testlib-build-vega-${{ needs.get-date.outputs.date }}
                  restore-keys: |
                      testlib-build-vega

            - name: Run Testlib GPU Tests
              working-directory: ${{ github.workspace }}/tests
              run: ./main.py run --length=very-long -vvv -j $(nproc) --host gcn_gpu --uid SuiteUID:tests/gem5/gpu/test_gpu_pannotia.py:gpu-apu-se-pannotia-color-maxmin-1k-128k-VEGA_X86-gcn_gpu-opt

            - name: Upload results
              if: success() || failure()
              uses: actions/upload-artifact@v4.0.0
              with:
                  name: gpu_tests_pannotia_color_maxmin_${{github.sha}}_RUN_${{github.run_id}}_ATTEMPT_${{github.run_attempt}}
                  path: tests/testing-results
                  retention-days: 7

    gpu-test-pannotia-color-max:
        runs-on: [self-hosted, linux, x64]
        container: ghcr.io/gem5/gcn-gpu:latest
        timeout-minutes: 720 # 12 hours
        needs: get-date

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: develop

            - name: Cache build/VEGA_X86
              uses: actions/cache@v4
              with:
                  path: build/VEGA_X86
                  key: testlib-build-vega-${{ needs.get-date.outputs.date }}
                  restore-keys: |
                      testlib-build-vega

            - name: Run Testlib GPU Tests
              working-directory: ${{ github.workspace }}/tests
              run: ./main.py run --length=very-long -vvv -j $(nproc) --host gcn_gpu --uid SuiteUID:tests/gem5/gpu/test_gpu_pannotia.py:gpu-apu-se-pannotia-color-max-1k-128k-VEGA_X86-gcn_gpu-opt

            - name: Upload results
              if: success() || failure()
              uses: actions/upload-artifact@v4.0.0
              with:
                  name: gpu_tests_pannotia_color_max_${{github.sha}}_RUN_${{github.run_id}}_ATTEMPT_${{github.run_attempt}}
                  path: tests/testing-results
                  retention-days: 7

    gpu-test-pannotia-fw-hip:
        runs-on: [self-hosted, linux, x64]
        container: ghcr.io/gem5/gcn-gpu:latest
        timeout-minutes: 2160 # 36 hours
        needs: get-date

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: develop

            - name: Cache build/VEGA_X86
              uses: actions/cache@v4
              with:
                  path: build/VEGA_X86
                  key: testlib-build-vega-${{ needs.get-date.outputs.date }}
                  restore-keys: |
                      testlib-build-vega

            - name: Run Testlib GPU Tests
              working-directory: ${{ github.workspace }}/tests
              run: ./main.py run --length=very-long -vvv -j $(nproc) --host gcn_gpu --uid SuiteUID:tests/gem5/gpu/test_gpu_pannotia.py:gpu-apu-se-pannotia-fw-hip-1k-128k-VEGA_X86-gcn_gpu-opt

            - name: Upload results
              if: success() || failure()
              uses: actions/upload-artifact@v4.0.0
              with:
                  name: gpu_tests_pannotia_fw_hip_${{github.sha}}_RUN_${{github.run_id}}_ATTEMPT_${{github.run_attempt}}
                  path: tests/testing-results
                  retention-days: 7

    dramsys-tests:
        runs-on: [self-hosted, linux, x64]
        container: ghcr.io/gem5/ubuntu-24.04_all-dependencies:latest
        timeout-minutes: 4320 # 3 days
        steps:
            - uses: actions/checkout@v4
            - name: Checkout DRAMSys
              working-directory: ${{ github.workspace }}/ext/dramsys
              run: git clone https://github.com/tukl-msd/DRAMSys --branch v5.0 --depth 1 DRAMSys

              # gem5 is built separately because it depends on the DRAMSys library
            - name: Build gem5
              working-directory: ${{ github.workspace }}
              run: scons build/ALL/gem5.opt -j $(nproc)

            - name: Run DRAMSys Checks
              working-directory: ${{ github.workspace }}
              run: |
                  ./build/ALL/gem5.opt configs/example/gem5_library/dramsys/arm-hello-dramsys.py
                  ./build/ALL/gem5.opt configs/example/gem5_library/dramsys/dramsys-traffic.py
                  ./build/ALL/gem5.opt configs/example/dramsys.py
    weekly-tests:
        # The dummy job is used to indicate whether the weekly tests have
        # passed or not. This can be used as status check for pull requests.
        # I.e., if we want to stop pull requests from being merged if the
        # weekly tests are failing we can add this job as a required status
        # check.
        runs-on: ubuntu-latest
        needs:
            - testlib-very-long-tests
            - dramsys-tests
            - gpu-test-hacc
            - gpu-test-lulesh
            - gpu-test-pannotia-bc
            - gpu-test-pannotia-color-maxmin
            - gpu-test-pannotia-color-max
            - gpu-test-pannotia-fw-hip
        steps:
            - run: echo "This weekly tests have passed."
